.tool-versions, pom.xml, src/main/java/cloud/prefab/client/ClientAuthenticationInterceptor.java, src/main/java/cloud/prefab/client/ConfigClient.java, src/main/java/cloud/prefab/client/FeatureFlagClient.java, src/main/java/cloud/prefab/client/PrefabCloudClient.java, src/main/java/cloud/prefab/client/RateLimitClient.java, src/main/java/cloud/prefab/client/config/ConfigLoader.java, src/main/java/cloud/prefab/client/config/ConfigResolver.java, src/main/java/cloud/prefab/client/config/ResolverElement.java, src/test/java/cloud/prefab/client/FeatureFlagClientTest.java, src/test/java/cloud/prefab/client/PrefabCloudClientTest.java, src/test/java/cloud/prefab/client/RateLimitClientTest.java, src/test/java/cloud/prefab/client/config/ConfigLoaderTest.java, src/test/java/cloud/prefab/client/config/ConfigResolverTest.java
Feature flags are much more advanced now, supporting segmentation & rules.
=> Major update to use our new domain model

src/main/java/cloud/prefab/client/FeatureFlagClient.java, src/main/java/cloud/prefab/client/config/ConfigResolver.java, src/main/java/cloud/prefab/client/config/ResolverElement.java, src/test/java/cloud/prefab/client/HarnessServer.java, src/test/java/cloud/prefab/client/config/ConfigResolverTest.java
Add in the custom logic so that variants are passed down to envs for feature flags.
Fix bug with multiple segments all->any.
=> Feature Flags passing test harness

README.md, pom.xml, src/main/java/cloud/prefab/client/ConfigClient.java, src/main/java/cloud/prefab/client/FeatureFlagClient.java, src/test/java/cloud/prefab/client/FeatureFlagClientTest.java, src/test/java/cloud/prefab/client/config/ConfigResolverTest.java
Bump deps to latest, remove apache HTTP client dep. Last PR focused on cruft cleanup I promise 😄
=> More cleanup

src/main/java/cloud/prefab/client/ConfigClient.java, src/main/java/cloud/prefab/client/PrefabCloudClient.java, src/main/java/cloud/prefab/client/config/ConfigLoader.java, src/test/java/cloud/prefab/client/PrefabOptionsTest.java, src/test/java/cloud/prefab/client/config/ConfigLoaderTest.java, src/test/resources/.prefab.default.config.yaml, src/test/resources/.prefab.test.config.yaml, src/test/resources/.prefab.unit_tests.config.yaml, src/test/resources/override_directory/.prefab.default.config.yaml
=> support nested config in yaml

src/main/java/cloud/prefab/client/ConfigClient.java, src/main/java/cloud/prefab/client/PrefabCloudClient.java, src/main/java/cloud/prefab/client/PrefabInitializationTimeoutException.java, src/main/java/cloud/prefab/client/config/ConfigResolver.java, src/test/java/cloud/prefab/client/ConfigClientTest.java
Add LocalOnly mode.
Add OnInitializationFailure options
=> Local Mode & OnInitFalures

pom.xml, src/main/java/cloud/prefab/client/FeatureFlagClient.java, src/main/java/cloud/prefab/client/PrefabCloudClient.java, src/main/java/cloud/prefab/client/config/ConfigResolver.java, src/main/java/cloud/prefab/client/config/Match.java, src/test/java/cloud/prefab/client/FeatureFlagClientTest.java, src/test/java/cloud/prefab/client/IntegrationTest.java, src/test/java/cloud/prefab/client/config/ConfigResolverTest.java, src/test/java/cloud/prefab/client/integration/IntegrationTestFunction.java
This fixes the client after the changes to data model around segments. It's all green against the new integration test data
=> Updates for new data model

src/main/java/cloud/prefab/client/ConfigClient.java, src/main/java/cloud/prefab/client/ConfigClientImpl.java, src/main/java/cloud/prefab/client/PrefabCloudClient.java, src/main/java/cloud/prefab/client/internal/ConfigClientImpl.java, src/test/java/cloud/prefab/client/ConfigClientTest.java, src/test/java/cloud/prefab/client/FeatureFlagClientTest.java, src/test/java/cloud/prefab/client/config/ConfigResolverTest.java, src/test/java/cloud/prefab/client/config/logging/JavaUtilLoggingConfigListenerTest.java, src/test/java/cloud/prefab/client/config/logging/Log4j1ConfigListenerTest.java, src/test/java/cloud/prefab/client/config/logging/Log4j2ConfigListenerTest.java, src/test/java/cloud/prefab/client/config/logging/LogbackConfigListenerTest.java, src/test/java/cloud/prefab/client/value/AbstractLiveValueTest.java
Moves the implementation to ConfigClientImpl
=> Extract an Interface from ConfigClient

src/main/java/cloud/prefab/client/internal/ConfigClientImpl.java
so scheduled executor keeps scheduling
redo of https://github.com/prefab-cloud/prefab-cloud-java/pull/26
=> Catch all exceptions in checkpoint loader

client/src/main/java/cloud/prefab/client/value/AbstractLiveValue.java, client/src/main/java/cloud/prefab/client/value/FixedValue.java, client/src/main/java/cloud/prefab/client/value/LiveBoolean.java, client/src/main/java/cloud/prefab/client/value/LiveDouble.java, client/src/main/java/cloud/prefab/client/value/LiveLong.java, client/src/main/java/cloud/prefab/client/value/LiveString.java, client/src/main/java/cloud/prefab/client/value/Value.java, client/src/test/java/cloud/prefab/client/integration/IntegrationTestInput.java, client/src/test/java/cloud/prefab/client/value/AbstractLiveValueTest.java
Expose a `getMaybe()` method on LiveValue so developers can chain off the optional as needed
Change `or` to `orElse` to match the way java Optionals work rather than the google/guava Optional
Change FixedValue to use java Optional
Adds logging
=> Value tweaks

client/src/main/java/cloud/prefab/client/Options.java, client/src/main/java/cloud/prefab/client/config/ConfigLoader.java, client/src/main/java/cloud/prefab/client/config/ConfigResolver.java, client/src/main/java/cloud/prefab/client/internal/ConfigClientImpl.java, client/src/test/java/cloud/prefab/client/PrefabOptionsTest.java, client/src/test/java/cloud/prefab/client/config/ConfigLoaderTest.java, client/src/test/java/cloud/prefab/client/config/UpdatingConfigResolverTest.java, client/src/test/resources/.prefab.unit_tests.config.yaml
This takes care of a number of issues found in testing, see individual commits for more info
=> Miscellaneous Client fixes

client/src/main/java/cloud/prefab/client/config/ConfigLoader.java, client/src/test/java/cloud/prefab/client/config/ConfigLoaderTest.java
This builds out the ability to load feature flags with criterion etc to be equivalent to our ruby client
=> Load feature flags from local yaml files

client/src/main/java/cloud/prefab/client/config/ConfigElement.java, client/src/main/java/cloud/prefab/client/config/ConfigResolver.java, client/src/main/java/cloud/prefab/client/config/UpdatingConfigResolver.java, client/src/main/java/cloud/prefab/client/internal/ConfigClientImpl.java, client/src/main/java/cloud/prefab/client/internal/LoggerStatsAggregator.java, logback-listener/src/main/java/cloud/prefab/client/config/logging/LogbackTurboFilter.java
A bunch of relatively low-hanging optimizations I noticed while doing some benchmarking and profiling.
None of these things are a cache that needs expiring when data changes; that work will be more complex and something to do later.
=> Performance improvements

client/src/main/java/cloud/prefab/client/config/logging/MDCTargetedLoggingHelper.java, client/src/main/java/cloud/prefab/client/config/logging/TargetedLoggingHelper.java, client/src/test/java/cloud/prefab/client/config/logging/MDCTargetedLoggingHelperTest.java
* Resolve issue where MDC did not like being set to null
* Add auto-closable context for managing lifetime of MDC value setting
=> Targeted logging improvements

client/src/main/java/cloud/prefab/client/internal/ConfigResolver.java, client/src/main/java/cloud/prefab/client/internal/IntRangeWrapper.java, client/src/test/java/cloud/prefab/client/internal/ConfigResolverTest.java, client/src/test/java/cloud/prefab/client/internal/IntRangeWrapperTest.java
Simple initial implementation of time/int range
=> Support time range

.gitignore, client/pom.xml, pom.xml
Relocate guava, failsafe to ease installs in some environments
=> Shade dependencies

log4j-two-listener/README.md, log4j-two-listener/pom.xml, log4j-two-listener/src/main/java/cloud/prefab/client/config/logging/Log4jLevelMapper.java, log4j-two-listener/src/main/java/cloud/prefab/client/config/logging/PrefabContextFilter.java, log4j-two-listener/src/test/java/cloud/prefab/client/config/logging/PrefabContextFilterTest.java, logback-listener/README.md
This adds a context-aware dynamic logging filter for log4j (2) with the same capabilities as the Logback implementation we've had for some time
=> Log4j logfilter

client/src/main/java/cloud/prefab/client/Options.java, client/src/main/java/cloud/prefab/client/internal/ConfigClientImpl.java, client/src/main/java/cloud/prefab/client/internal/ConfigResolver.java, client/src/main/java/cloud/prefab/client/internal/LookupContext.java, client/src/test/java/cloud/prefab/client/integration/BaseIntegrationTestCaseDescriptor.java, client/src/test/java/cloud/prefab/client/internal/ConfigClientImplTest.java, client/src/test/java/cloud/prefab/client/internal/ConfigRuleEvaluatorTest.java, client/src/test/java/cloud/prefab/client/internal/LookupContextTest.java, client/src/test/java/cloud/prefab/client/internal/TelemetryManagerTest.java, client/src/test/java/cloud/prefab/client/internal/UpdatingConfigResolverTest.java, client/src/test/java/cloud/prefab/client/internal/WeightedValueEvaluatorTest.java
We've eliminated the standalone namespace concept in favor of setting one inside the context
=> Removes support for namespace

client/src/main/java/cloud/prefab/client/internal/PrefabHttpClient.java
remove some no-longer used methods
=> Handle 401/403 error code with consistent error log message.

client/src/main/java/cloud/prefab/client/internal/LookupContext.java, client/src/test/java/cloud/prefab/client/integration/telemetry/ExampleContextIntegrationTestCaseDescriptor.java, client/src/test/java/cloud/prefab/client/internal/ConfigRuleEvaluatorTest.java, client/src/test/java/cloud/prefab/client/internal/LookupContextTest.java, client/src/test/java/cloud/prefab/client/internal/WeightedValueEvaluatorTest.java
Most significant change is making the client use contexts in a case insensitive manner to bring it in line with our clients in other languages
=> Update integration test data 0.2.4.3

client/src/main/java/cloud/prefab/client/ConfigClient.java, client/src/main/java/cloud/prefab/client/LiveValuesConfigClient.java, client/src/main/java/cloud/prefab/client/TypedConfigClient.java, client/src/main/java/cloud/prefab/client/config/ConfigValueUtils.java, client/src/main/java/cloud/prefab/client/internal/ConfigClientCore.java, client/src/main/java/cloud/prefab/client/internal/ConfigClientImpl.java, client/src/main/java/cloud/prefab/client/internal/TypedConfigClientImpl.java, client/src/main/java/cloud/prefab/client/value/LiveDuration.java, client/src/test/java/cloud/prefab/client/internal/TypedConfigClientImplTest.java
This adds a set of methods eg `long getLong(String key, long defaultValue, @Nullable PrefabContextSetReadable context)` for long, double, String, List<String> and Duration
=> Add native typed getters

client/src/main/java/cloud/prefab/client/internal/SseConfigStreamingSubscriber.java
downgrade to debug because its expected
=> Handle GOAWAY logging in the correct location ---

client/pom.xml, log4j-two-listener/pom.xml, logback-listener/pom.xml, micronaut/pom.xml, pom.xml
this updates the proto submodule to get semver/regex operators
=> Add Regex semver ops

client/pom.xml, client/src/main/java/cloud/prefab/client/internal/ConfigRuleEvaluator.java, client/src/main/java/cloud/prefab/client/internal/SemanticVersion.java, client/src/test/java/cloud/prefab/client/internal/ConfigRuleEvaluatorTest.java, client/src/test/java/cloud/prefab/client/internal/SemanticVersionTest.java, log4j-two-listener/pom.xml, logback-listener/pom.xml, micronaut/pom.xml, pom.xml
this adds support for regex pattern matching operators (PROP_MATCHES/PROP_DOES_NOT_MATCH) and semantic versioning (PROP_SEMVER_LESS_THAN/PROP_SEMVER_EQUAL/PROP_SEMVER_GREATER_THAN)
=> Implements Regex semver ops

client/pom.xml, log4j-two-listener/pom.xml, logback-listener/pom.xml, micronaut/pom.xml, pom.xml
=> Consolidate the prettier-java plugin goal binding.

pom.xml
Changes to make sure the jitpack profile compiles and doesn't try to use git over ssh
=> Jitpack debug

jitpack.yml
Updates jitpack configuration to make it work again
=> Updates jitpack configration
